repository_type: pipeline

lint:
  files_exist:
    - assets/nf-core-fetchdatairidanext_logo_light.png
    - docs/images/nf-core-fetchdatairidanext_logo_light.png
    - docs/images/nf-core-fetchdatairidanext_logo_dark.png
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - CODE_OF_CONDUCT.md
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/NfcoreTemplate.groovy
    - lib/WorkflowFetchdatairidanext.groovy
  files_unchanged:
    - assets/sendmail_template.txt
    - assets/email_template.html
    - lib/NfcoreTemplate.groovy
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - .gitignore
    - assets/email_template.txt
    - docs/README.md
    - LICENSE
  pipeline_name_conventions: False
  actions_awsfulltest: False
  multiqc_config:
    - report_comment
  nextflow_config:
    - custom_config
    - manifest.name
    - manifest.homePage
    - params.max_cpus
    - params.max_memory
    - params.max_time
  readme:
    - nextflow_badge
